### ISSUE TITLE
keyboard cursor keys

### ISSUE THREAD

**Issue by DavidJRichards** [AndresNavarro82/vt52-fpga#4]
I have found in my version that the keyboard cursor controls give lower case ESC letter sequences a,b,c,d. According to the documents I have read these should be upper case, I have edited the keyboard file to suit and now I am able to use the keys. Using vt52-fpga as a linux terminal nano now works properly as a screen editor.
```
// up arrow (Esc-A)
@475
c1
@575
c1
@675
c1
@775
c1
// down arrow (Esc-B)
@472
c2
@572
c2
@672
c2
@772
c2
// right arrow (Esc-C)
@474
c3
@574
c3
@674
c3
@774
c3
// left arrow (Esc-D)
@46b
c4
@56b
c4
@66b
c4
@76b
c4
```

**Comment by AndresNavarro82** [comment]
Yeah, an oversight on my part.  I guess it shows that I don't use the arrow keys much...
Thanks, I'll fix it at once

**Comment by AndresNavarro82** [comment]
Should be fixed, didn't test it but seems like a pretty straightforward fix
